# Generated by Django 6.0.6 on 2026-06-29 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='library',
            field=models.ForeignKey(blank=True, help_text="Qaysi kutubxonaga tegishli bo'lim. Null bo'lsa - umumiy bo'lim.", limit_choices_to={'user_role': 'librarian'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to=settings.AUTH_USER_MODEL),
        ),
    ]
