# Generated by Django 6.0.5 on 2026-06-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_librarybook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarybook',
            name='price_per_day',
        ),
    ]
