# Generated by Django 6.0.5 on 2026-06-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_approved_customuser_library_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='library_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
