# Generated by Django 6.0.5 on 2026-06-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_library_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='library_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='library_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
